export const skills = () => {
  const skills = document.createElement('article');
  skills.classList.add('card');
  skills.innerHTML = `
    <h2>Skills and Associated Abilities</h2>
    <table>
      <thead>
        <tr>
          <th>Skill</th>
          <th>Ability</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Acrobatics</td>
          <td>Dexterity</td>
        </tr>
         <tr>
          <td>Animal Handling</td>
          <td>Dexterity</td>
        </tr>
         <tr>
          <td>Arcana</td>
          <td>Intelligence</td>
        </tr>
         <tr>
          <td>Athletics</td>
          <td>Strength</td>
        </tr>
        <tr>
          <td>Deception</td>
          <td>Charisma</td>
        </tr>
        <tr>
          <td>History</td>
          <td>Intelligence</td>
        </tr>
        <tr>
          <td>Insight</td>
          <td>Wisdom</td>
        </tr>
        <tr>
          <td>Intimidation</td>
          <td>Charisma</td>
        </tr>
        <tr>
          <td>Investigation</td>
          <td>Intelligence</td>
        </tr>
        <tr>
          <td>Medicine</td>
          <td>Wisdom</td>
        </tr>
        <tr>
          <td>Nature</td>
          <td>Intelligence</td>
        </tr>
        <tr>
          <td>Perception</td>
          <td>Wisdom</td>
        </tr>
        <tr>
          <td>Performance</td>
          <td>Charisma</td>
        </tr>
        <tr>
          <td>Persuasion</td>
          <td>Charisma</td>
        </tr>
        <tr>
          <td>Religion</td>
          <td>Intelligence</td>
        </tr>
        <tr>
          <td>Sleight of Hand</td>
          <td>Dexterity</td>
        </tr>
        <tr>
          <td>Stealth</td>
          <td>Dexterity</td>
        </tr>
        <tr>
          <td>Survival</td>
          <td>Wisdom</td>
        </tr>
      </tbody>
    </table>
  `;
  return skills;
};
